version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Main LocalStack API endpoint
    environment:
      - SERVICES=s3  # Enable only the S3 service
      - DEBUG=1
    volumes:
      - "localstack_data:/var/lib/localstack"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  localstack_data:
  pgdata:
